<a href="https://colab.research.google.com/github/annamaartensson/dd2424project/blob/issue%2F2/rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf

In [76]:
path_to_file = tf.keras.utils.get_file('prideandprejudice.txt', 'https://www.gutenberg.org/cache/epub/42671/pg42671.txt')
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')

725256/725256 [==============================] - 0s 0us/step


In [ ]:
vocabulary = sorted(set(text))
ids_to_chars =
chars_to_ids =

In [74]:
class RNN:

  class Grads:

    def __init__(self, m, K):
      self.b = tf.Variable(tf.zeros_initializer()(shape = (K)))
      self.c = tf.Variable(tf.zeros_initializer()(shape = (K)))
      self.U = tf.Variable(tf.zeros_initializer()(shape = (m, K)))
      self.W = tf.Variable(tf.zeros_initializer()(shape = (m, m)))
      self.V = tf.Variable(tf.zeros_initializer()(shape = (K, m)))

    def compute(self):
      pass

  def __init__(self, seq_length, m, K, sig):
    self.seq_length = seq_length
    self.m = m
    self.K = K
    self.b = tf.Variable(tf.zeros_initializer()(shape = (m)))
    self.c = tf.Variable(tf.zeros_initializer()(shape = (K)))
    self.U = tf.Variable(tf.random_normal_initializer(mean=0.0, stddev=sig)(shape = (m, K)))
    self.W = tf.Variable(tf.random_normal_initializer(mean=0.0, stddev=sig)(shape = (m, m)))
    self.V = tf.Variable(tf.random_normal_initializer(mean=0.0, stddev=sig)(shape = (K, m)))
    self.h0 = tf.Variable(tf.zeros_initializer()(shape = (m)))

  def forwardPass(self, X):
    P = tf.Variable(tf.zeros_initializer()(shape = (self.K, self.seq_length)))
    H = tf.Variable(tf.zeros_initializer()(shape = (self.m, self.seq_length+1)))
    A = tf.Variable(tf.zeros_initializer()(shape = (self.m, self.seq_length)))
    H[:,0].assign(self.h0)
    for t in range(self.seq_length):
      A[:,t].assign(tf.tensordot(self.W, H[:,t], 1) + tf.tensordot(self.U, X[:,t], 1) + self.b)
      H[:,t+1].assign(tf.math.tanh(A[:,t]))
      P[:,t].assign(tf.raw_ops.Softmax(logits = (tf.tensordot(self.V, H[:,t+1], 1) + self.c)))
    return P, H, A

  def backwardPass(self, X, Y, P, H, A):
    grads = RNN.Grads(self.m, self.K)

    return grads

  def loss(self, X, Y, P):
    pass

  def train(self, eta, steps):
    #TODO: replace with real data/batches
    X = tf.Variable(tf.zeros_initializer()(shape = (80, 25)))
    Y = tf.Variable(tf.zeros_initializer()(shape = (80, 25)))
    P, H, A = self.forwardPass(X)
    grads = self.backwardPass(X, Y, P, H, A)


In [75]:
rnn = RNN(25, 100, 80, 0.01)
x = tf.Variable(tf.zeros_initializer()(shape = (80, 25)))
rnn.forwardPass(x)

(<tf.Variable 'Variable:0' shape=(80, 25) dtype=float32, numpy=
 array([[0.0125, 0.0125, 0.0125, ..., 0.0125, 0.0125, 0.0125],
        [0.0125, 0.0125, 0.0125, ..., 0.0125, 0.0125, 0.0125],
        [0.0125, 0.0125, 0.0125, ..., 0.0125, 0.0125, 0.0125],
        ...,
        [0.0125, 0.0125, 0.0125, ..., 0.0125, 0.0125, 0.0125],
        [0.0125, 0.0125, 0.0125, ..., 0.0125, 0.0125, 0.0125],
        [0.0125, 0.0125, 0.0125, ..., 0.0125, 0.0125, 0.0125]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(100, 26) dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(100, 25) dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        